
version: 2
jobs:
  one:
    docker:
      - image: circleci/php:7.1.16

    working_directory: '~/project'

    steps:
      - checkout
      - run: ls
      - run: composer install -n --prefer-dist
      - run: echo "A first hello"
      - run: php codeception-example/codecept.phar
      - run: php codecept.phar run
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
