
version: 2
jobs:
  one:
    docker:
      - image: circleci/php:7.1.16

    working_directory: '~/project'

    steps:
      - checkout
      - run: ls
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run: composer install -n --prefer-dist
      - run: echo "A first hello"
      - run: php codecept.phar build
      - run: php codecept.phar run
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
